# Generated by Django 3.2.4 on 2021-06-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0002_remove_image_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='imageFile',
        ),
    ]
