# Generated by Django 3.2.4 on 2021-06-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadApp', '0003_rename_img_image_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageFile',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
